# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3" do
  version "0.2.41"

  on_macos do
    on_intel do
      sha256 "99f03e11eb50c3063ea02bff8a438411a2b7e0b78391cfdbc582e1bb0eb4828f"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0820bac50058457ecba2b72d784b0dd773faf6a1e1d740d3f4bd6085ca51cc01"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd15f52e88a34a88e05e0ff854b1ef146433b834544289bd16db6fb28663e21e"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "94bd1bb957e56adc266ed331bc92e7bc58d0235c595c59e72fa36d37068fdab7"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3"
  desc "Personal Claude Code session manager — CLI + web GUI"
  homepage "https://github.com/binhsonnguyen/ccc"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "c3-bin"
  binary "c3-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/c3-bin", "#{staged_path}/c3-server"]
    end
  end

  zap launchctl: [
      "com.c3.server",
    ],
    trash: [
      "~/.local/share/c3",
      "~/.local/state/c3",
      "~/Library/LaunchAgents/com.c3.server.plist",
    ]

  caveats <<~EOS
    Enable the `c3` command in your shell rc:

      bash/zsh:  eval "$(c3-bin shell-init zsh)"
      fish:      c3-bin shell-init fish | source

    The GUI server listens on 127.0.0.1:7755 by default. Override with
    C3_SERVER_PORT=N (or =0 for a random port).

    Run it always-on in the background (replaces `brew services start c3`):

      c3 service start        # stop with: c3 service stop
  EOS
end
