# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3" do
  version "0.2.50"

  on_macos do
    on_intel do
      sha256 "3766ead4175eec511fdda944ba106ac29228cdb3fa66886cba555e6e87cd4bc6"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f59bfa04c21ca1fe2ffccd1a837e374ff935a306cbb2aa539058c983e5103480"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d1085cd8b54cb71aa731edacac0e2ca203e6aadf895d92f546cc9beb45f88708"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b33c3e20887b574f3a66690cebbc25b8baa0cf216e7d91e76b74418a6f17b04"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3"
  desc "Personal Claude Code session manager — CLI + web GUI"
  homepage "https://github.com/binhsonnguyen/ccc"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "c3-bin"
  binary "c3-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/c3-bin", "#{staged_path}/c3-server"]
    end
  end

  zap launchctl: [
      "com.c3.server",
    ],
    trash: [
      "~/.local/share/c3",
      "~/.local/state/c3",
      "~/Library/LaunchAgents/com.c3.server.plist",
    ]

  caveats <<~EOS
    Enable the `c3` command in your shell rc:

      bash/zsh:  eval "$(c3-bin shell-init zsh)"
      fish:      c3-bin shell-init fish | source

    The GUI server listens on 127.0.0.1:7755 by default. Override with
    C3_SERVER_PORT=N (or =0 for a random port).

    Run it always-on in the background (replaces `brew services start c3`):

      c3 service start        # stop with: c3 service stop
  EOS
end
