# This file was generated by GoReleaser. DO NOT EDIT.
cask "c3" do
  version "0.2.39"

  on_macos do
    on_intel do
      sha256 "0fbf2900bf43eac70cd6f9c79f0aef76b1def5789371f127519857f80fee674b"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "21d70b0cfca3c258c2a17a2f98b209eab258c81afcef11b0d3996e6111ef4a37"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d40ff48957ccfec0515af9bf667f8309973cc41a28265ad02cc9af6eef0c9c37"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0d6c9fc36410e8856ddd8f11245768624604a30c7d78dbae8d10aeccac152f7"
      url "https://github.com/binhsonnguyen/ccc/releases/download/v#{version}/ccc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "c3"
  desc "Personal Claude Code session manager — CLI + web GUI"
  homepage "https://github.com/binhsonnguyen/ccc"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "c3-bin"
  binary "c3-server"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/c3-bin", "#{staged_path}/c3-server"]
    end
  end

  zap launchctl: [
      "com.c3.server",
    ],
    trash: [
      "~/.local/share/c3",
      "~/.local/state/c3",
      "~/Library/LaunchAgents/com.c3.server.plist",
    ]

  caveats <<~EOS
    Enable the `c3` command in your shell rc:

      bash/zsh:  eval "$(c3-bin shell-init zsh)"
      fish:      c3-bin shell-init fish | source

    The GUI server listens on 127.0.0.1:7755 by default. Override with
    C3_SERVER_PORT=N (or =0 for a random port).

    Run it always-on in the background (replaces `brew services start c3`):

      c3 service start        # stop with: c3 service stop
  EOS
end
