# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C3 < Formula
  desc "Personal Claude Code session manager — CLI + web GUI"
  homepage "https://github.com/binhsonnguyen/ccc"
  version "0.2.36"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.2.36/ccc_0.2.36_darwin_amd64.tar.gz"
      sha256 "f2e572b407e8e35dc96755187768aab16d676e5bdf4560e9bf075a5f6986b659"

      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        # share/fish/vendor_functions.d resolves to fish's auto-load
        # path under HOMEBREW_PREFIX. fish_function_path DSL is not in
        # scope inside the per-arch define_method(:install) blocks
        # goreleaser generates, so we hand-roll the path.
        (share/"fish/vendor_functions.d").install "shell/c3.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.2.36/ccc_0.2.36_darwin_arm64.tar.gz"
      sha256 "a8a1fa9e4f028f114c065ab80a7b2da8df2b70d11dfc253e82795ff94e095d6c"

      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        # share/fish/vendor_functions.d resolves to fish's auto-load
        # path under HOMEBREW_PREFIX. fish_function_path DSL is not in
        # scope inside the per-arch define_method(:install) blocks
        # goreleaser generates, so we hand-roll the path.
        (share/"fish/vendor_functions.d").install "shell/c3.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.2.36/ccc_0.2.36_linux_amd64.tar.gz"
      sha256 "04decf0a956e193b53b011880373c74f89cb47d508cd3951e939384fcc6d0602"
      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        # share/fish/vendor_functions.d resolves to fish's auto-load
        # path under HOMEBREW_PREFIX. fish_function_path DSL is not in
        # scope inside the per-arch define_method(:install) blocks
        # goreleaser generates, so we hand-roll the path.
        (share/"fish/vendor_functions.d").install "shell/c3.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.2.36/ccc_0.2.36_linux_arm64.tar.gz"
      sha256 "446c60416c9571d853f29b4df8ac9a4d8a47aaa0b677de1d8f676c81ac79c9d2"
      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        # share/fish/vendor_functions.d resolves to fish's auto-load
        # path under HOMEBREW_PREFIX. fish_function_path DSL is not in
        # scope inside the per-arch define_method(:install) blocks
        # goreleaser generates, so we hand-roll the path.
        (share/"fish/vendor_functions.d").install "shell/c3.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the `c3` command in bash/zsh, add to your shell rc:

        source "$(brew --prefix)/etc/c3/c3.sh"

      Fish users: the function is auto-loaded.

      The GUI server listens on 127.0.0.1:7755 by default. Override
      with C3_SERVER_PORT=N (or =0 for a random port).

      Optional: run c3-server in the background via brew services so
      `c3 gui` opens the browser instantly without spawning anything:

        brew services start c3

      (Service mode disables the idle auto-shutdown.)
    EOS
  end

  service do
    run [opt_bin/"c3-server"]
    keep_alive true
    log_path var/"log/c3-server.log"
    error_log_path var/"log/c3-server.log"
    # Idle shutdown makes sense when c3 gui spawns the server on
    # demand, but defeats the point of running as a service.
    environment_variables C3_SERVER_IDLE_MINUTES: "0"
  end

  test do
    system "#{bin}/c3-bin", "--version"
    system "#{bin}/c3-server", "--version"
  end
end
