# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C3 < Formula
  desc "Personal Claude Code session manager — CLI + web GUI"
  homepage "https://github.com/binhsonnguyen/ccc"
  version "0.1.1"
  license "MIT"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.1.1/ccc_0.1.1_darwin_amd64.tar.gz"
      sha256 "d51517f3d12c22063a815602f011c4b02e4de41f35837bc4b2ca7e1e6ad1954b"

      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        fish_function_path.install "shell/c3.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.1.1/ccc_0.1.1_darwin_arm64.tar.gz"
      sha256 "9c7627316c46400d4cd930c2ef8c3a27b669d6549a6bd13b07e37f2e481bfd97"

      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        fish_function_path.install "shell/c3.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.1.1/ccc_0.1.1_linux_amd64.tar.gz"
      sha256 "48cd3c28bbc4f6f15c15e21330b67e6fa590cbcf8c87bfe4a92ca531901f41e7"
      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        fish_function_path.install "shell/c3.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/binhsonnguyen/ccc/releases/download/v0.1.1/ccc_0.1.1_linux_arm64.tar.gz"
      sha256 "41cd4368a38f27a99c3b52147ce0a1093c8b796078a816b255ac067f2627a19f"
      define_method(:install) do
        bin.install "c3-bin"
        bin.install "c3-server"
        (etc/"c3").install "shell/c3.sh"
        fish_function_path.install "shell/c3.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable the `c3` command in bash/zsh, add to your shell rc:

        source "$(brew --prefix)/etc/c3/c3.sh"

      Fish users: the function is auto-loaded.

      The GUI server listens on 127.0.0.1:7755 by default. Override
      with C3_SERVER_PORT=N (or =0 for a random port).
    EOS
  end

  test do
    system "#{bin}/c3-bin", "--version"
    system "#{bin}/c3-server", "--version"
  end
end
